name: Build and Push to Docker Hub

# 触发条件：推送到 main 分支或创建标签时
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Docker 构建x（可选，支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        # 4. 提取镜像标签（分支名/标签名，如 latest 或 v1.0.0）
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wangchenjun521/docker-ubuntu-wcj-test  # 替换为 Docker Hub 镜像名
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short
            
      # 5. 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Dockerfile 所在目录（. 表示根目录）
          file: ./Dockerfile  # 指定 Dockerfile 路径
          push: true  # 推送到仓库
          tags: ${{ steps.meta.outputs.tags }}  # 自动生成的标签
          labels: ${{ steps.meta.outputs.labels }}  # 自动生成的镜像标签
          cache-from: type=gha  # 使用 GitHub Actions 缓存加速构建
          cache-to: type=gha,mode=max  # 保存缓存到 GitHub
